[env:native]
platform = native
build_flags = -Wall -Wextra -std=gnu++17 -DUNITY_INCLUDE_FLOAT -DNATIVE_BUILD -I${PROJECT_TEST_DIR}
lib_deps = Unity
test_build_src = yes
test_ignore = test_sensors

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -Wall -Wextra -std=gnu++17 -DUNITY_INCLUDE_FLOAT
lib_deps =
    Unity
    NimBLE-Arduino
monitor_speed = 115200
upload_speed = 921600
